Stack and its real life applications
div-bargali/Data-Structures-and-Algorithms pull request #839
Opened 2020-10-31 14:25 UTC by dalalvarun

## Stack and its real life applications

###Stack implementation using array
###Stack implementation using Linked List
###Multiple Stack
###Parenthesis Checker
###Infix to Postfix
###Infix to Prefix
###Prefix evaluation
###Postfix Evaluation

Write here what you have changed in codebase

### #838   #

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder.
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file.

This wasn't assigned to me. But I have a PR lined up.

2020-11-01 17:21 UTC, div-bargali commented
@dalalvarun Your implementation code is in the wrong directory.

2020-12-07 05:45 UTC, hemanth-kotagiri requested changes
Hello, @dalalvarun. Thank you for your PR.
Please consider fixing the issues that I addressed individually in the comments.
Format your code well in whichever file applicable.

Thanks!

2020-12-07 05:45 UTC, hemanth-kotagiri commented on C++/Data-Structures/Stacks/Evaluate Postfix Expression.cpp
> +    gets(input);
``gets`` was not declared in this scope. Please fix this by including the required headers.

2020-12-07 05:45 UTC, hemanth-kotagiri commented on C/Data-Structures/Stacks/Evaluate Prefix Expression.cpp
> +    cout<<"\nThe evaluation is: "<<peek(top);
Add an escape character ``\n`` or ``endl``.

2020-12-07 05:45 UTC, hemanth-kotagiri commented on C/Data-Structures/Stacks/Infix to Postfix Conversion.cpp
> +    }
Add a new line escape character or ``endl`` here as well.

2020-12-07 05:45 UTC, hemanth-kotagiri commented on C/Data-Structures/Stacks/Parenthesis Checker using Stacks.cpp
> +    gets(exp);
``gets`` is not declared in this scope.

2021-09-10 13:40 UTC, closed without merging